"""Vectorize the Mungyeong Paragliding logo into per-glyph SVG paths.

The source logo is a tiny 290x68 PNG, so each colour layer is upsampled,
smoothed and traced with potrace to get crisp paths at any size.
Output: src/logo_paths.js (window.LOGO, coordinates in original logo pixel units).
"""
import json
import sys

import numpy as np
import potrace
from PIL import Image
from scipy import ndimage

SRC = sys.argv[1] if len(sys.argv) > 1 else "assets/logo_original.png"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/logo_paths.js"
UP = 10  # upsampling factor

img = np.asarray(Image.open(SRC).convert("RGBA")).astype(np.float32) / 255.0
H, W = img.shape[:2]
r, g, b, a = img[..., 0], img[..., 1], img[..., 2], img[..., 3]

is_red = r > b + 0.15
is_line = (b > r) & (r > 0.16)  # thin light-blue riser lines
is_blue = (b > r + 0.15) & ~is_line

yy, xx = np.mgrid[0:H, 0:W]
wing_zone = (yy < 36) | (xx >= 266)

layers = {
    "red": a * is_red,
    "text": a * (is_blue & ~wing_zone),
    "wing": a * (is_blue & wing_zone),
}


def upsample(cov, smooth):
    im = Image.fromarray(cov.astype(np.float32), mode="F")
    big = np.asarray(im.resize((W * UP, H * UP), Image.BICUBIC))
    if smooth:
        big = ndimage.gaussian_filter(big, smooth)
    return big


def trace(mask, alphamax):
    bm = potrace.Bitmap(~mask)  # potracer treats True as background
    plist = bm.trace(turdsize=12, alphamax=alphamax, opticurve=True, opttolerance=0.2)
    parts = []
    s = 1.0 / UP
    f = lambda p: f"{p.x * s:.3f} {p.y * s:.3f}"
    for curve in plist:
        parts.append("M" + f(curve.start_point))
        for seg in curve.segments:
            if seg.is_corner:
                parts.append("L" + f(seg.c) + "L" + f(seg.end_point))
            else:
                parts.append("C" + f(seg.c1) + " " + f(seg.c2) + " " + f(seg.end_point))
        parts.append("Z")
    return "".join(parts)


def bbox(mask):
    ys, xs = np.where(mask)
    return [xs.min() / UP, ys.min() / UP, (xs.max() + 1) / UP, (ys.max() + 1) / UP]


# glyph column cuts in original pixel units
CUTS = [
    ("문", "red", 0, 32.5), ("경", "red", 32.5, 65.5),
    ("패", "text", 65.5, 98.5), ("러", "text", 98.5, 131.5),
    ("글", "text", 131.5, 165), ("라", "text", 165, 200.5),
    ("이", "text", 200.5, 232), ("딩", "text", 232, 268),
]

def drop_specks(mask, min_frac=0.03):
    """Remove stray bits (riser-line pixels) smaller than min_frac of the largest blob."""
    lab, n = ndimage.label(mask)
    if n == 0:
        return mask
    sizes = ndimage.sum(mask, lab, range(1, n + 1))
    keep = np.isin(lab, 1 + np.where(sizes >= sizes.max() * min_frac)[0])
    return keep


big = {k: drop_specks(upsample(v, 1.1 if k != "wing" else 2.5) > 0.5) for k, v in layers.items()}
X = np.arange(W * UP)[None, :] / UP

out = {"width": W, "height": H, "glyphs": []}
for ch, layer, x0, x1 in CUTS:
    m = big[layer] & (X >= x0) & (X < x1)
    out["glyphs"].append({"ch": ch, "layer": layer, "d": trace(m, 0.45), "bbox": bbox(m)})

wing = big["wing"]
out["wing"] = {"d": trace(wing, 1.1), "bbox": bbox(wing)}
# riser lines, measured by hand from the source (x1, y1, x2, y2)
out["lines"] = [
    [200.6, 27.0, 223.0, 38.2],
    [214.0, 19.5, 223.0, 38.2],
    [262.5, 32.0, 256.0, 50.0],
    [273.0, 42.0, 256.0, 50.0],
]
with open(OUT, "w") as fh:
    fh.write("// generated by vectorize_logo.py\nwindow.LOGO = " + json.dumps(out, ensure_ascii=False) + ";\n")
print("glyphs", len(out["glyphs"]), "bytes", sum(len(gl["d"]) for gl in out["glyphs"]) + len(out["wing"]["d"]))
