// generated by make_paper.py
window.SPRITES = {
 "paper_bg": {
  "src": "../../assets/collage/paper_bg.jpg",
  "w": 1080,
  "h": 1920,
  "pad": 0
 },
 "sky0": {
  "src": "../../assets/collage/sky0.png",
  "w": 1260,
  "h": 140,
  "pad": 28
 },
 "sky1": {
  "src": "../../assets/collage/sky1.png",
  "w": 1260,
  "h": 146,
  "pad": 28
 },
 "sky2": {
  "src": "../../assets/collage/sky2.png",
  "w": 1260,
  "h": 103,
  "pad": 28
 },
 "sky3": {
  "src": "../../assets/collage/sky3.png",
  "w": 1260,
  "h": 112,
  "pad": 28
 },
 "sky4": {
  "src": "../../assets/collage/sky4.png",
  "w": 1260,
  "h": 141,
  "pad": 28
 },
 "sun": {
  "src": "../../assets/collage/sun.png",
  "w": 220,
  "h": 220,
  "pad": 28
 },
 "cloud0": {
  "src": "../../assets/collage/cloud0.png",
  "w": 330,
  "h": 150,
  "pad": 28
 },
 "cloud1": {
  "src": "../../assets/collage/cloud1.png",
  "w": 300,
  "h": 130,
  "pad": 28
 },
 "cloud2": {
  "src": "../../assets/collage/cloud2.png",
  "w": 260,
  "h": 110,
  "pad": 28
 },
 "cloud3": {
  "src": "../../assets/collage/cloud3.png",
  "w": 240,
  "h": 100,
  "pad": 28
 },
 "mtn0": {
  "src": "../../assets/collage/mtn0.png",
  "w": 1280,
  "h": 420,
  "pad": 28
 },
 "mtn1": {
  "src": "../../assets/collage/mtn1.png",
  "w": 1280,
  "h": 420,
  "pad": 28
 },
 "mtn2": {
  "src": "../../assets/collage/mtn2.png",
  "w": 1280,
  "h": 420,
  "pad": 28
 },
 "mtn3": {
  "src": "../../assets/collage/mtn3.png",
  "w": 1280,
  "h": 380,
  "pad": 28
 },
 "hill0": {
  "src": "../../assets/collage/hill0.png",
  "w": 1280,
  "h": 520,
  "pad": 28
 },
 "hill1": {
  "src": "../../assets/collage/hill1.png",
  "w": 1280,
  "h": 520,
  "pad": 28
 },
 "hill2": {
  "src": "../../assets/collage/hill2.png",
  "w": 1280,
  "h": 520,
  "pad": 28
 },
 "ground0": {
  "src": "../../assets/collage/ground0.png",
  "w": 1280,
  "h": 480,
  "pad": 28
 },
 "ground1": {
  "src": "../../assets/collage/ground1.png",
  "w": 1280,
  "h": 360,
  "pad": 28
 },
 "photo_tandem": {
  "src": "../../assets/collage/photo_tandem.png",
  "w": 600,
  "h": 804,
  "pad": 28,
  "inner": [
   20,
   20,
   560,
   764
  ],
  "srcScale": 0.5925925925925926,
  "srcCrop": [
   200,
   40,
   1145,
   1330
  ]
 },
 "photo_crew": {
  "src": "../../assets/collage/photo_crew.png",
  "w": 686,
  "h": 583,
  "pad": 28,
  "srcScale": 0.6515301085883515,
  "srcCrop": [
   200,
   360,
   1213,
   1215
  ],
  "border": 13
 },
 "logo_card": {
  "src": "../../assets/collage/logo_card.png",
  "w": 1010,
  "h": 300,
  "pad": 28
 },
 "tape0": {
  "src": "../../assets/collage/tape0.png",
  "w": 170,
  "h": 50,
  "pad": 28
 },
 "tape1": {
  "src": "../../assets/collage/tape1.png",
  "w": 170,
  "h": 50,
  "pad": 28
 },
 "tape2": {
  "src": "../../assets/collage/tape2.png",
  "w": 170,
  "h": 50,
  "pad": 28
 },
 "tape3": {
  "src": "../../assets/collage/tape3.png",
  "w": 170,
  "h": 50,
  "pad": 28
 },
 "red_strip": {
  "src": "../../assets/collage/red_strip.png",
  "w": 1300,
  "h": 290,
  "pad": 28
 },
 "label_yellow": {
  "src": "../../assets/collage/label_yellow.png",
  "w": 400,
  "h": 100,
  "pad": 28
 },
 "tile0": {
  "src": "../../assets/collage/tile0.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile1": {
  "src": "../../assets/collage/tile1.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile2": {
  "src": "../../assets/collage/tile2.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile3": {
  "src": "../../assets/collage/tile3.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile4": {
  "src": "../../assets/collage/tile4.png",
  "w": 70,
  "h": 40,
  "pad": 28
 },
 "tile5": {
  "src": "../../assets/collage/tile5.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile6": {
  "src": "../../assets/collage/tile6.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile7": {
  "src": "../../assets/collage/tile7.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "tile8": {
  "src": "../../assets/collage/tile8.png",
  "w": 120,
  "h": 170,
  "pad": 28
 },
 "grain": {
  "src": "../../assets/collage/grain.png",
  "w": 1080,
  "h": 1920,
  "pad": 0
 }
};
